[package]
name = "pumpfun_sniper_trading"
version = "0.1.0"
edition = "2021"

[dependencies]
sol-trade-sdk = { path = "../.." }
sol-parser-sdk = { workspace = true }
solana-sdk = { workspace = true }
solana-commitment-config = { workspace = true }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
